### ISSUE TITLE
Correção das Diretivas de Segurança

### ISSUE THREAD

**Issue by botelhojp** [demoiselle/frontend#12]
- [x] Falta testar as diretivas "dml-*"

Ex.: `<div dml-has-role="ADMINISTRATOR"> ... </div>`

Teste feito na sidebar menu. Esconde opções de administração para não administradores.

**Comment by marcelofns** [comment]
https://github.com/demoiselle/frontend/commit/5e04ce68c27aafc4811df70c54f0b83e0f3b3989
