### ISSUE TITLE
Form validation/Serviço de validação

### ISSUE THREAD

**Issue by botelhojp** [demoiselle/frontend#14]

**Comment by leonardomerlin** [comment]
Vou tentar especificar melhor essa issue e vamos alterando conforme necessário...

---

Necessidade: automatizar o processo de validação de formulários.

Soluções possíveis consiste em: Interceptar os erros da resposta da requisição e

- ou buscar por `$('[name="campo_com_erro"]')` e marcar com CSS o campo.
- ou tentar utilizar a directive `NgForm` no mapeamento específico dos campos e marcação do `NgModel` específico.

(priorizar a segunda opção)

**Comment by botelhojp** [comment]
Regra para nome do campo: **metodoRest.tipoDaEntidade.atributo**. Exemplo: _persist.User.name_

**Comment by marcelofns** [comment]
Adicionado Observable ao serviço Http permitindo que a aplicação seja avisada quando ocorrerem erros de validação: https://github.com/demoiselle/frontend/commit/26377561095fd0b8dd6ef117e76e8f3f7298e74a

Documentação GitBook sobre validação e formas de tratamento dos erros no frontend: https://demoiselle.gitbooks.io/documentacao-frontend/content/validacao-com-demoiselle-3.html
