### ISSUE TITLE
Componente/serviço de notificação Toastr

### ISSUE THREAD

**Issue by marcelofns** [demoiselle/frontend#5]

**Comment by marcelofns** [comment]
Criado serviço de notificação. 
Para popup de confirmação a recomendação é utilizar a biblioteca **angular-confirmation-popover**.
Falta:
- Criar opção e implementação de web notifications
- Criar módulo que conterá esse serviço, talvez o módulo Common

**Comment by botelhojp** [comment]
Cancelado. Será documentado o uso das notificações na issue #9
