### ISSUE TITLE
401 Unauthorized: HttpService redirecionar para login

### ISSUE THREAD

**Issue by marcelofns** [demoiselle/frontend#7]
Verificar diferença entre não autenticado e não autorizado (401, 403)
Verificar ajuste no bakckend

**Comment by marcelofns** [comment]
Implementado no commit https://github.com/demoiselle/frontend/commit/aeb94502f45276d6382874b67d1e5a95980146b7

**Comment by leonardomerlin** [comment]
# Testado!

O componente realiza o redirect ao receber 401. Segue algumas anotações:
- Se a aplicação frontend estiver na página do redirect ("/login", por exemplo) e essa página fizer alguma chamada que retorne 401, a aplicação pode entrar em loop.
- O componente foi alterado para permitir tanto uma `string` quanto uma `function` no parâmetro `unAuthorizedRoute`.
  - caso `string`: será utilizado o `Router` do "angular/router"
  - caso `function`: apenas será chamada a função passada (callback)

---

Sobre a nova descrição da issue,
> Verificar diferença entre não autenticado e não autorizado (401, 403)
> Verificar ajuste no bakckend

sugiro fechar esta issue a abrir outra apenas para especificar/documentar/padronizar os possíveis tratamentos de erros.
