### ISSUE TITLE
Documentação Gitbook

### ISSUE THREAD

**Issue by marcelofns** [demoiselle/frontend#9]
Itens para documentar:
- [x] Visão Geral do Projeto
- [x] Módulos: Security, Http e notificação (como utilizar)
- [x] Aplicações Exemplos
- [x] Generator

**Comment by marcelofns** [comment]
Documentação e ajustes: https://github.com/demoiselle/frontend/commit/99aaa0870aebd60d59e1936909e2fcbd166ae3de

**Comment by botelhojp** [comment]
https://github.com/demoiselle/frontend/tree/master/modules/%40demoiselle/security
